apiVersion: v2
name: openreports
description: A Helm chart for installing openreports APIs.
version: v0.0.0
appVersion: latest
annotations:
  artifacthub.io/home: https://github.com/openreports/openreports
  artifacthub.io/sources: https://github.com/openreports/openreports
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/crds: |
    - kind: ClusterReport
      version: v1alpha1
      name: clusterreports.openreports.io
      displayName: Cluster Report
      description: ClusterReport is the Schema for the ClusterReport API
    - kind: Report
      version: v1alpha1
      name: reports.openreports.io
      displayName: Report
      description: Report is the Schema for the Report API
    

